name: Publish to GitHub Pages

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Move to source code directory
        run: MechanicalSyncClient
        
      - name: List source code files
        run: dir .
