name: Publish to GitHub Pages

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: MechanicalSyncClient

      - name: List files
        run: dir .
